name: Add label to pull requests with reviewer

on:
  pull_request_review:
    types: [edited, submitted]

jobs:
  labelWhenReviewer:
    name: Add label when reviewed
    runs-on: ubuntu-latest
    steps:
    - name: Add label when reviewed
      uses: justia/ga-add-remove-label@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTION: "REVIEWED"
